server:
   port: 8083
   tomcat:
      uri-encoding: UTF-8   
security:
   basic:
      enabled: false
token:
   secret: 9SyECk96oDsTmXfogIieDI0cD/8FpnojlYSUJT5U9I/FGVmBz5oskmjOR8cbXTvoPjX+Pq/T/b1PqpHX0lYm0oCBjXWICA==
logging:
   path: log
spring.jpa.show-sql: true
spring:
   application:
     name: productService
   data:
      mongodb:
         host: 127.0.0.1
         port: 27017
         database: arquitecture
         username: arquitectureapp
         password: arquitectureapp
   datasource: 
      driverClassName: com.mongodb.Mongo
   rabbitmq:
      host: docker-1
      port: 5672
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      