server:
   port: 8080
   tomcat:
      uri-encoding: UTF-8   
security:
   basic:
      enabled: false
token:
   secret: 9SyECk96oDsTmXfogIieDI0cD/8FpnojlYSUJT5U9I/FGVmBz5oskmjOR8cbXTvoPjX+Pq/T/b1PqpHX0lYm0oCBjXWICA==
logging:
   path: log
spring.jpa.show-sql: true
spring:
   application:
     name: agregationService
   rabbitmq:
      host: docker-1
      port: 5672
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/