user:
  image: java:openjdk-8u45-jdk
  working_dir: /app
  volumes:
    - ../../user/build/libs:/app
  ports:
    - "8082"
  external_links:
    - rabbitmq
    - mongodb
    - eureka
  environment:
    SPRING_PROFILES_ACTIVE: docker
  command: java -jar /app/user.jar  
  
product:
  image: java:openjdk-8u45-jdk
  working_dir: /app
  volumes:
    - ../../product/build/libs:/app
  ports:
    - "8083"
  external_links:
    - rabbitmq
    - mongodb
    - eureka
  environment:
    SPRING_PROFILES_ACTIVE: docker
  command: java -jar /app/product.jar 

agregation:
  image: java:openjdk-8u45-jdk
  working_dir: /app
  volumes:
    - ../../agregation/build/libs:/app
  ports:
    - "8080:8080"
  links:
    - user
    - product
  external_links:
    - rabbitmq
    - mongodb
    - eureka
  environment:
    SPRING_PROFILES_ACTIVE: docker
  command: java -jar /app/agregation.jar 
